### ISSUE TITLE
Entrevista 

### ISSUE THREAD

**Issue by ErikCuevas03** [SistemasTecTlaxiaco/actividad-8-entrevista-equipo-y#3]
[Entrevista.docx](https://github.com/SistemasTecTlaxiaco/actividad-8-entrevista-equipo-y/files/9955600/Entrevista.docx)

**Comment by Daisy-GonzalezLita12** [comment]
Hola compañero bien hecho 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
